### ISSUE TITLE
Rename all properties with hyphens in them to underscores

### ISSUE THREAD

**Issue by eglassman** [cephcyn/alignpaper#1]
ObservableHQ is having trouble with 'averb-s' as a name.

**Comment by eglassman** [comment]
@cephcyn Can you rerun the BERT with this small change and let me know when I can pull the new version of the CSV?

**Comment by cephcyn** [comment]
Done! https://github.com/cephcyn/alignpaper/commit/6293220eda0a901d5c112de9fc8e2febc35d120d
